### ISSUE TITLE
Some symbols not displayed in WSL bash. 

### ISSUE THREAD

**Issue by coriolinus** [TomasTomecek/pretty-git-prompt#23]
# expected behavior 
```shell
master +1
```

# encountered behavior 
```shell 
master  1
```

Possibly there could be a command line switch which would choose ASCII only symbols?

**Comment by TomasTomecek** [comment]
Honestly, I have no idea what WSL bash is. And it seems it's not capable of displaying unicode characters, so you should raise that with WSL bash upstream.

This problem has very easy solution: all you need to do, is create config file for pretty-git-prompt and set symbols yourself:

```
$ pretty-git-prompt create-default-config
Configuration file created at "/home/.../.config/pretty-git-prompt.yml"
```

And then just edit the config `~/.config/pretty-git-prompt.yml` file and change the symbols to whatever you prefer. Please, let me know if it's understandable to edit the config file.

**Comment by coriolinus** [comment]
WSL bash is the bash which runs inside the Windows Subsystem for Linux, which gives you a full Linux system on any machine which runs Windows 10. I'd agree that the fundamental issue is that WSL can't display unicode characters, though I'm not sure where Microsoft expects us to go with bug reports for that.

Unfortunately, the `create-default-config`  command appears not to work:

```shell
coriolinus@robocomp:~$ pretty-git-prompt create-default-config && ls -lah ~/.config/ | grep pretty

coriolinus@robocomp:~$ pretty-git-prompt -h
pretty-zsh-prompt 0.1.0
Tomas Tomecek <tomas@tomecek.net>
Get `git status` inside your shell prompt.

USAGE:
    pretty-git-prompt [FLAGS] [OPTIONS] [SUBCOMMAND]

FLAGS:
    -d, --debug      Print debug messages, useful for identifying issues.
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --config <FILE>    Use the given config file.

SUBCOMMANDS:
    create-default-config
    help                     Prints this message or the help of the given subcommand(s)

coriolinus@robocomp:~$ pretty-git-prompt -V
pretty-zsh-prompt 0.1.0

coriolinus@robocomp:~$ pretty-git-prompt create-default-config --debug
error: Found argument '--debug' which wasn't expected, or isn't valid in this context

USAGE:
    pretty-git-prompt create-default-config

For more information try --help
```

**Comment by TomasTomecek** [comment]
Thanks for such detailed output: I can reproduce locally. The issue seems to be that the `create-default-config` command works only when inside git repository.

**Comment by TomasTomecek** [comment]
This should be fixed via https://github.com/TomasTomecek/pretty-git-prompt/commit/57441751134acbe4262ac0fb46d12c44c8fcaf27, I also submitted new release so you should be able to test this out once the build finishes and binaries are available via github release
