### ISSUE TITLE
feature request: display git sha1 with version

### ISSUE THREAD

**Issue by aerickson** [TomasTomecek/pretty-git-prompt#24]
When developing, the version number often isn't enough to easily identify a build. It would be handy if `-V` also gave the git sha1 that the build was compiled at. I guess it could be incorrect if there are uncommitted changes ("-dirty" or similar could be appended to indicate it's not a fully reproducible build).

```
~ > pretty-git-prompt -V
pretty-zsh-prompt 0.0.1 (53f06c)
~ >
```

**Comment by TomasTomecek** [comment]
Definitely makes sense. I hope that clap will be able to do it somehow.

**Comment by TomasTomecek** [comment]
This is fixed now. The commit hash and repository state is picked up from environment (set in the makefile), example:

```
$ ./target/release/pretty-git-prompt -V
pretty-git-prompt 0.1.2 (8501b87, dirty)
```
