### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ignatenkobrain** [TomasTomecek/pretty-git-prompt#41]
I would recommend you to set up @dependabot ;)

**Comment by TomasTomecek** [comment]
I haven't touched this project for quite some time, it works just fine for me. I recall it doesn't even build with the newest rust and deps.

**Comment by ignatenkobrain** [comment]
It should build fine with new rust (probably with really small tweaks) and updating dependencies should not be that hard :)

**Comment by TomasTomecek** [comment]
I'll try to take a look at this in coming days, thanks Igor!

**Comment by TomasTomecek** [comment]
The bot is set up. The deps really need an update, I can't even compile p-g-p with rust 1.32.
