### ISSUE TITLE
crates.io calls the license "non-standard"

### ISSUE THREAD

**Issue by cuviper** [TomasTomecek/pretty-git-prompt#55]
FYI, using `license-file` without `license` leads to crates.io listing this crate as having a "non-standard" license, even though it's really just MIT.

I filed rust-lang/cargo#8537 on this, and I used your crate as an example. But please don't take that as any kind of blame/shame -- your crate just happened to be the first that ripgrep found on my disk. :slightly_smiling_face:

**Comment by TomasTomecek** [comment]
fixed in #68
